#
# Defines environment variables.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Ensure that a non-login, non-interactive shell has a defined environment.
if [[ ( "$SHLVL" -eq 1 && ! -o LOGIN ) && -s "${ZDOTDIR:-$HOME}/.zprofile" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprofile"
fi

export LSCOLORS=ExFxBxDxCxegedabagacad

export HOMEBREW_NO_ANALYTICS=1

export JAVA_HOME=$(/usr/libexec/java_home -v 17)

export MAVEN_HOME="/usr/local/opt/maven/libexec/"
export MAVEN_OPTS="-Xms512m -Xmx2048m"

export GRADLE_OPTS="-Dorg.gradle.daemon=true"
