#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

# Online help
unalias run-help
autoload run-help
HELPDIR=/usr/local/share/zsh/help

# Source machine-specific config
if [[ -s "${ZDOTDIR:-$HOME}/.zlocal" ]]; then
  source "${ZDOTDIR:-$HOME}/.zlocal"
fi

# Source awscli completion
if [[ -s "/usr/local/share/zsh/site-functions/_aws" ]]; then
    source "/usr/local/share/zsh/site-functions/_aws"

fi

# Useful aliases
alias fixow='/System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/LaunchServices.framework/Versions/A/Support/lsregister -kill -r -domain local -domain user;killall Finder;echo "Open With has been rebuilt, Finder will relaunch"'

alias ...='cd ../..'
alias ....='cd ../../..'
alias .....='cd ../../../..'

alias history='history 0'

# Git amend all
alias gcaf='git commit --all --amend --reuse-message HEAD'

# Git unapply
alias gsu='git stash show -p | git apply -R'

alias gitk="gitk --all $1 2>/dev/null &"
